typography_spectrum: 0.2594782372470945
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6070579960942268
  lightness: 0.2850058116018772
  saturation: 0.7830486674793065
  rhythmicContrast: 0.20447294623591006
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9452140990179032
analytics:
  google: null
  facebook: null
  twitter: null
name: moon.wtf
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Red Panda
description: has your back
purpose: []
